### ISSUE TITLE
Breaks vim-rails gf

### ISSUE THREAD

**Issue by Soliah** [AndrewRadev/ember_tools.vim#12]
When I have both this and vim-rails installed, running `gf` on say a controller in a Rails project just opens up a netrw window.

Removing this plugin makes it work again. The ember functionality does work with both plugins installed so maybe some better detection of when in an ember project like what vim-rails does would be good.

**Comment by AndrewRadev** [comment]
Good catch. I tried to pull some magic tricks to get vim-rails and ember_tools to work well together, but it seems I hadn't quite figured it out.

I think I've managed to get it working this time. Could you try out the latest version in master and let me know if it works for you?

**Comment by Soliah** [comment]
Master fixes the vim-rails incompatibility! However I'm finding the `gf` functionality doesn't seem to work reliably for actions and import paths. I'll raise a separate issue for those.
