### ISSUE TITLE
E216: No such group or event: TextChanged <buffer> call ember_tools#syntax#MarkPrivateArea()

### ISSUE THREAD

**Issue by sergii-bond** [AndrewRadev/ember_tools.vim#15]
I get this error on MacOS upon startup of `vim <any_name>.js`. 

```
Error detected while processing function ember_tools#Init..<SNR>53_DefineJavascriptAutocommands:
line   25: 
E216: No such group or event: TextChanged <buffer> call ember_tools#syntax#MarkPrivateArea()
```

MacOS version El Capitan 10.11.4.
The error is not present when running on Ubuntu 16.04 with same .vimrc file and same .vim directory.

**Comment by AndrewRadev** [comment]
I'm guessing the problem is that the Vim on your Mac is slightly older and doesn't support the `TextChange` autocommand. I've added a guard to check for its existence. Could you try it out now, and let me know if it works as expected?

**Comment by sergii-bond** [comment]
vim version is 7.3 on both systems. 
The new version doesn't show the error, thank you for the fix!
