### ISSUE TITLE
Issue with Support `gf` for finding components instantiated via angle-brackets

### ISSUE THREAD

**Issue by NoahFisher** [AndrewRadev/ember_tools.vim#17]
First of all, thanks for this plugin!

I recently upgraded it to utilize the new angle bracket navigation that #16 introduced, but it doesn't work correctly for me.

Here's a component in my route template: 
```
            <Reports::PayPeriods::SpreadsheetLinks
              @tagName=""
              @buttonClass="button-link"
              @downloadButtonCopy="CSV"
              @isDrilldownAvailable={{payPeriod.isDrilldownAvailable}}
              @payPeriodId={{payPeriod.id}}
            />
```

Here is the error I'm receiving: 
![image](https://user-images.githubusercontent.com/3476655/86380116-957ac000-bc40-11ea-951c-6240ac12f70a.png)

**Comment by AndrewRadev** [comment]
> First of all, thanks for this plugin!

Thank you for the kind words :).

Seems there was a problem with a case-insensitive regex -- I assume you have `ignorecase` on, which affected a particular substitution.

I've pushed a fix -- let me know if it works correctly now.

**Comment by NoahFisher** [comment]
@AndrewRadev - Yes this has fixed the issue. Thanks very much!
