### ISSUE TITLE
Add index routes for 'gf'

### ISSUE THREAD

**Issue by lllama** [AndrewRadev/ember_tools.vim#2]
At the moment, the `gf` command in the router will not work if the app uses an index.js rather than <route-name>.js.

If possible, it would be great if the plugin tested for the index.js variant if the named version does not exist.

**Comment by AndrewRadev** [comment]
I've just pushed a commit that should support this use case as well. Could you try it out and let me know if it works for you?

**Comment by lllama** [comment]
hey - sorry for the late reply but I've tried the latest commit and this seems to work now. Thanks again for the plugin. Feel free to close.
