### ISSUE TITLE
Open new tab for "gf" command

### ISSUE THREAD

**Issue by kidonchu** [AndrewRadev/ember_tools.vim#5]
Could you add an option to open a new tab with "gf" command? Currently it opens the referenced component/template in the same tab instead of new tab.

I have great interest in this project and maybe I could make a PR for this feature if I learn enough about how the vim plugin works.

**Comment by AndrewRadev** [comment]
Actually, you can use `<c-w>gf` to open the link in a new tab. This is standard Vim behaviour and you can read more about it with [`:help CTRL-W_gf`](http://vimhelp.appspot.com/windows.txt.html#CTRL%2dW_gf).

If you generally prefer `gf` to open things in a new tab, maybe you can remap `gf` to `<c-w>gf`, but I would try to get used to the built-in option first.

**Comment by kidonchu** [comment]
Thanks a lot for the help. Looks like I still have a lot to learn about vim.
I appreciate all the work you are putting into this plugin.
